### ISSUE TITLE
Theme on Loading Screen

### ISSUE THREAD

**Issue by tarun-menta** [iith-dashboard/iith-dashboard-pwa#13]
When the app starts up, the theme defaults to light while displaying the losing screen. This may be a react quirk, but it would be better if it matches the chosen theme

**Comment by RachitKeertiDas** [comment]
I don't think it is a React quirk, It was probably me either being lazy or avoiding it due to clashes with the purple theme at that time.

Now that the theme is much more refined, it looks like this:

![image](https://user-images.githubusercontent.com/51906583/152973708-66d72927-37d1-4b2b-8abd-f679926a5018.png)

It's currently limited to the dark theme, due to reasons outlined in #15

**Comment by RachitKeertiDas** [comment]
Oops, I thought you meant the login screen.
Fixed the issue for both of them now.

(The dark theme constraint remains, however)
